action.yml

This should resolve the issue of inputs not being passed along to the setup script.
Residual issue: the checks here still use the main version of the action, so this won't be active until merged.

[inputs] https://github.com/actions/runner/issues/665

---

.github/workflows/cvmfs_config_package.yml
README.md
action.yml
setup-cvmfs.sh

@wdconinc I didn't test this, but I expect this to work since it's very similar to the other `${INPUT_CVMFS...}` input variables.
This should allow use to install our own `cvmfs-config-eessi` package (see https://github.com/EESSI/filesystem-layer/releases).

add support for specifying alternate cvmfs-config package to install via $INPUT_CVMFS_CONFIG_PACKAGE

---

.github/workflows/cvmfs_http_proxy.yml

Setting cvmfs_http_proxy to anything other than DIRECT results in no access, so don't try to read any /cvmfs dirs.

[cvfms_http_proxy] for auto proxy, do not try to access site

---

.github/workflows/cvmfs_config_package.yml
.github/workflows/cvmfs_http_proxy.yml
.github/workflows/cvmfs_repositories.yml
.github/workflows/macos.yml
.github/workflows/minimal-usage.yml
README.md
action.yml
createConfig.sh
setup-cvmfs.sh

- This extends the the action to work on macOS with the limitions to mount the repository under `/User/share`
- Maps all variables from [Client Parameters](https://cvmfs.readthedocs.io/en/stable/apx-parameters.html#client-parameters) to same name github action parameters
- All default paramers are in the action and none in the scripts
- The default.local how by default only `CVMFS_CLIENT_PROFILE='signle'` and `CVMFS_USE_CDN='yes'` as `CVMFS_HTTP_PROXY` is implied by `CVMFS_USE_CDN`
I am still having problem to configure that the testing would work for PRs but
```diff
- uses: cvmfs-contrib/github-action-cvmfs@main
+ uses: ${{ github.repository }}@main
```
But does not want. So there is a bit of work here still

Add more options and macOS support

---

.github/workflows/macos.yml
.github/workflows/minimal-usage.yml
README.md

Add build badges and fix typos

Typos and badges

---

README.md
action.yml

@petricm unless you have any other wip, I think we can tag v2 after this.

Fix some typos, formatting

---

setup-cvmfs.sh

The return code of `cmvfs_config setup` should be checked in the action as it is not the last command in the `setup-cvmfs.sh` script.

Check return code cvmfs_config at the end of installation

---

setup-cvmfs.sh

`brew cask install osxfuse` does not work anymore and need to be replaced with `brew install --cask osxfuse`

Update deprecated brew behaviour

---

setup-cvmfs.sh

With cvmfs 2.8.0 there is a need for a newer version of fuse, however osxfuse was renamed to macfuse, so if you do
```
brew install --cask osxfuse
```
you get version 3.11, but you need version 4.0, for which you need to call
```
brew install --cask macfuse
```
@vvolkl it's re-tag time again

change osxfuse for macfuse

---

.github/workflows/macos.yml
.github/workflows/ubuntu.yml

To catch breaking changes to the underlying platforms (e.g. https://github.com/cvmfs/cvmfs/issues/2882), run the testing workflow daily.

Run workflows MacOS and Ubuntu daily

---

.github/workflows/cvmfs_config_package.yml
.github/workflows/cvmfs_http_proxy.yml
.github/workflows/cvmfs_repositories.yml
.github/workflows/macos.yml
.github/workflows/ubuntu.yml
action.yml
setup-cvmfs.sh

Previously we were using an option `run_local_checkout` instead of `action/checkout` followed by `uses: .`. The latter requires fewer branches and is more robust.

Use current directory for action workflow

---

setup-cvmfs.sh

This adds a warning for users of this action to let them know that MacOS support will disappear with the end of life of macos-10.15 in GitHub Actions in a month from now.
The idea is to merge this warning and retag v2 with these changes to ensure people see the warning.
Changes cherry-picked from #17.

Warn about upcoming MacOS phase out

---

action.yml
setup-cvmfs.sh

This uses action/cache for apt downloads (*.deb and lists) to prevent hitting CERN apt repo locations frequently with download requests.

Use action/cache for apt downloads

---

.github/workflows/ubuntu.yml

The ubuntu-18.04 is being deprecated and emitting warnings.
"The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002."

ci(chore): replace ubuntu-18.04 with ubuntu-22.04

---

.github/workflows/cvmfs_config_package.yml
.github/workflows/cvmfs_http_proxy.yml
.github/workflows/cvmfs_repositories.yml
.github/workflows/ubuntu.yml

This is more than just a chore in that GitHub has been starting to generate warnings about actions/checkout@v2.
"Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout"

ci(chore): upgrade to actions/checkout@v3

---

action.yml

"Starting today runner version 2.298.2 will begin to warn you if you use the save-state or set-output commands via stdout." [GitHub blog, 2022-10-11](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
And wouldn't you know it... All my jobs warning endlessly!
This modifies the `lsb-release` step to use the new way of providing outputs.

fix: replace set-output with $GITHUB_OUTPUT

---

setup-cvmfs.sh

This adds folding groups in the logging output.

feat: add logging groups

---

action.yml

The warnings [promised](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.) for October 23 have finally arrived. This updates the underlying actions/cache from v3 to v4.

fix: update actions/cache from v3 to v4 (node.js v20 support)

---

.github/workflows/macos.yml
README.md
action.yml
setup-cvmfs.sh

While macfuse is no longer an option, there is now a nice alternative with fuse-t. This PR adds experimental support (I've successfully tested it with the nightly build, but there is no released cvmfs version with fuse-t support yet). @YBelikov may be able to add it in the context of a GSoC project.
'Synthetic firmlinks' are used to create /cvmfs , since the root file system is now read-only on macos.
One todo: need to check if we actually need the homebrew action or it can be moved somewhere else.

Re-enable experimental support for cvmfs on macos runners

---

action.yml
setup-cvmfs.sh

Since github actions are run in Azure where there is not normally a proxy defined, leaving cvmfs_http_proxy unset results in a call to WLCG Web Proxy Auto Discovery (WPAD).  If there are enough of them in a short period of time (125 requests within 15 minutes) from the one organization (as defined by Maxmind) then the WPAD directs clients to backup proxies, which causes an alarm.  That alarm was triggered yesterday.  This PR fixes that problem by defaulting cvmfs_http_proxy to DIRECT.
After merging I would like a new tag, and I will also backport to v4 where we'll need another tag.  The [specific action](https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit/blob/main/.github/workflows/cvmfs-ci.yml#L28) that likely triggered the alarm was using v4.

Make cvmfs_http_proxy default to DIRECT

---

action.yml
setup-cvmfs.sh

Cherry-pick #35 to the actions-cache-v4 branch.

make cvmfs_http_proxy default to DIRECT (v4)

---

.github/workflows/cvmfs_config_package.yml

This PR updates the CI test to use software.eessi.io instead of pilot.eessi-hpc.org, and updates the config package to v0.5.0. See https://www.eessi.io/docs/repositories/pilot/.

fix(ci): pilot.eessi-hpc.org -> software.eessi.io

---

COPILOT_INSTRUCTION.md

This PR extracts the `COPILOT_INSTRUCTION.md` file from #45 into its own branch for better organization. This change is an internal documentation change only.

docs: Add Copilot instructions

---

.devcontainer/devcontainer.json

This PR adds a devcontainer configuration for development of this action, `github-action-cvmfs`, and the future extension into a devcontainer feature that provides cvmfs functionality to devcontainers directly.

feat: Add local devcontainer configuration with npm, docker, git-lfs
